name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      REMOTE_PATH: /opt/aliapi

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: grant permission
        run: chmod +x ./gradlew

      - name: build fat jar
        run: ./gradlew shadowJar

      - name: rename jar
        run: mv server/build/libs/server-all.jar server/build/libs/aliapi.jar

      - name: upload JAR
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: server/build/libs/aliapi.jar
          target: ${{ env.REMOTE_PATH }}
          strip_components: 2

      - name: restart remote service
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker restart api
